# Generated by Django 3.0.5 on 2020-04-09 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
