# Generated by Django 3.0.5 on 2020-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
