# Generated by Django 3.0.5 on 2020-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meta_titlee',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
