# Generated by Django 3.0.5 on 2020-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200409_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
