# Generated by Django 3.0.5 on 2020-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_formpage_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
