# Generated by Django 3.0.5 on 2020-04-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0012_auto_20200409_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='google_tag',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_tag',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_pixel', models.CharField(blank=True, max_length=2000)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
