# Generated by Django 3.0.5 on 2020-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200409_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='facebook_pixel',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='google_tag',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_pixel',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='google_tag',
        ),
        migrations.AddField(
            model_name='formpage',
            name='no_index_field',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='no_index_field',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='google_tag',
            field=models.CharField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
